<?php
/**
 * English Language File — Torymail
 */
return [

    // ─── Common ───────────────────────────────────────
    'save'              => 'Save',
    'cancel'            => 'Cancel',
    'delete'            => 'Delete',
    'edit'              => 'Edit',
    'add'               => 'Add',
    'close'             => 'Close',
    'send'              => 'Send',
    'reply'             => 'Reply',
    'reply_all'         => 'Reply All',
    'forward'           => 'Forward',
    'download'          => 'Download',
    'create'            => 'Create',
    'update'            => 'Update',
    'remove'            => 'Remove',
    'enable'            => 'Enable',
    'disable'           => 'Disable',
    'reset'             => 'Reset',
    'filter'            => 'Filter',
    'verify'            => 'Verify',
    'activate'          => 'Activate',
    'suspend'           => 'Suspend',
    'archive'           => 'Archive',
    'move'              => 'Move',
    'refresh'           => 'Refresh',
    'discard'           => 'Discard',
    'loading'           => 'Loading...',
    'processing'        => 'Processing...',
    'saving'            => 'Saving...',
    'sending'           => 'Sending...',
    'creating'          => 'Creating...',
    'resetting'         => 'Resetting...',
    'search'            => 'Search',
    'actions'           => 'Actions',
    'status'            => 'Status',
    'created'           => 'Created',
    'yes'               => 'Yes',
    'no'                => 'No',
    'all'               => 'All',
    'none'              => 'None',
    'home'              => 'Home',
    'back'              => 'Back',
    'view_details'      => 'View details',
    'server_error'      => 'Server connection error',
    'confirm'           => 'Confirm',
    'proceed'           => 'Yes, proceed',
    'never'             => 'Never',
    'no_data'           => 'No data found',
    'required'          => 'Required',
    'optional'          => 'Optional',
    'success'           => 'Success',
    'error'             => 'Error',
    'warning'           => 'Warning',
    'done'              => 'Done!',
    'language'          => 'Language',

    // ─── Status badges ────────────────────────────────
    'active'            => 'Active',
    'inactive'          => 'Inactive',
    'disabled'          => 'Disabled',
    'banned'            => 'Banned',
    'suspended'         => 'Suspended',
    'pending'           => 'Pending',
    'sending_status'    => 'Sending',
    'sent'              => 'Sent',
    'failed'            => 'Failed',
    'verified'          => 'Verified',
    'running'           => 'Running',
    'blocked'           => 'Blocked',

    // ─── Roles ────────────────────────────────────────
    'role_admin'        => 'Admin',
    'role_user'         => 'User',

    // ─── Auth ─────────────────────────────────────────
    'login'             => 'Login',
    'register'          => 'Register',
    'logout'            => 'Logout',
    'login_title'       => 'Login — Torymail',
    'login_subtitle'    => 'Login to Torymail email system',
    'login_welcome'     => 'Welcome back!',
    'login_desc'        => 'Login to continue using Torymail.',
    'email'             => 'Email',
    'email_placeholder' => 'Enter email',
    'password'          => 'Password',
    'password_placeholder' => 'Enter password',
    'remember_me'       => 'Remember me',
    'forgot_password'   => 'Forgot password?',
    'no_account'        => "Don't have an account?",
    'register_now'      => 'Register now',
    'register_title'    => 'Register — Torymail',
    'register_subtitle' => 'Create a new account',
    'register_desc'     => 'Create a free account today.',
    'fullname'          => 'Full Name',
    'fullname_placeholder' => 'John Doe',
    'email_register_placeholder' => 'you@example.com',
    'password_min'      => 'Minimum 8 characters',
    'confirm_password'  => 'Confirm Password',
    'confirm_password_placeholder' => 'Re-enter password',
    'has_account'       => 'Already have an account?',
    'forgot_title'      => 'Forgot Password — Torymail',
    'forgot_subtitle'   => 'Password Recovery',
    'forgot_desc'       => 'Enter your email to receive a recovery link.',
    'forgot_email_placeholder' => 'Enter registered email',
    'send_recovery'     => 'Send Recovery Link',
    'remember_password' => 'Remember your password?',
    'system_tagline'    => 'Professional Email System',

    // ─── Admin Sidebar ────────────────────────────────
    'menu'              => 'Menu',
    'dashboard'         => 'Dashboard',
    'users'             => 'Users',
    'domains'           => 'Domains',
    'mailboxes'         => 'Mailboxes',
    'email_queue'       => 'Email Queue',
    'activity_logs'     => 'Activity Logs',
    'settings'          => 'Settings',
    'system_info'       => 'System Info',

    // ─── User Sidebar ─────────────────────────────────
    'compose'           => 'Compose',
    'mailbox'           => 'Mailbox',
    'inbox'             => 'Inbox',
    'starred'           => 'Starred',
    'drafts'            => 'Drafts',
    'spam'              => 'Spam',
    'trash'             => 'Trash',
    'management'        => 'Management',
    'contacts'          => 'Contacts',
    'templates'         => 'Templates',
    'filters'           => 'Filters',
    'labels'            => 'Labels',

    // ─── Admin Dashboard ──────────────────────────────
    'total_users'       => 'Total Users',
    'active_domains'    => 'Active Domains',
    'active_mailboxes'  => 'Active Mailboxes',
    'emails_today'      => 'Emails Today',
    'queue_pending'     => 'Queue Pending',
    'total_storage'     => 'Total Storage Used',
    'emails_last_30'    => 'Emails — Last 30 Days',
    'received'          => 'Received',
    'recent_activity'   => 'Recent Activity',
    'no_activity'       => 'No activity logged yet',
    'time'              => 'Time',
    'user'              => 'User',
    'action'            => 'Action',
    'details'           => 'Details',
    'ip'                => 'IP',

    // ─── Admin Users ──────────────────────────────────
    'all_users'         => 'All Users',
    'add_user'          => 'Add User',
    'name'              => 'Name',
    'role'              => 'Role',
    'storage'           => 'Storage',
    'last_activity'     => 'Last Activity',
    'max_domains'       => 'Max Domains',
    'storage_quota_mb'  => 'Storage Quota (MB)',
    'create_user'       => 'Create User',
    'ban'               => 'Ban',
    'unban'             => 'Unban',
    'ban_confirm'       => 'Ban this user?',
    'unban_confirm'     => 'Unban this user?',
    'ban_desc'          => "This will change the user's access.",
    'delete_user'       => 'Delete User?',
    'delete_user_desc'  => 'This action cannot be undone. All user data will be permanently deleted.',

    // ─── Admin Domains ────────────────────────────────
    'all_domains'       => 'All Domains',
    'add_domain'        => 'Add Domain',
    'domain'            => 'Domain',
    'domain_name'       => 'Domain Name',
    'owner'             => 'Owner',
    'select_user'       => '-- Select User --',
    'auto_verify'       => 'Auto-verify (skip DNS verification)',
    'verify_dns'        => 'Verify DNS',
    'suspend_domain'    => 'Suspend this domain?',
    'suspend_domain_desc' => 'This will affect all mailboxes under this domain.',
    'activate_domain'   => 'Activate this domain?',
    'delete_domain'     => 'Delete Domain?',
    'delete_domain_desc' => 'This will permanently delete the domain and all its mailboxes.',
    'shared'            => 'Shared',
    'shared_domain'     => 'Shared domain',
    'shared_domain_desc' => 'Shared domains allow all users to create mailboxes without adding their own domain.',
    'set_shared'        => 'Set as shared',
    'unset_shared'      => 'Remove shared',
    'system'            => 'System',
    'managed_by_admin'  => 'Managed by admin',

    // ─── Admin Mailboxes ──────────────────────────────
    'all_mailboxes'     => 'All Mailboxes',
    'used_quota'        => 'Used / Quota',
    'reset_password'    => 'Reset Password',
    'reset_password_for' => 'Reset password for:',
    'new_password'      => 'New Password',
    'disable_mailbox'   => 'Disable this mailbox?',
    'enable_mailbox'    => 'Enable this mailbox?',
    'delete_mailbox'    => 'Delete Mailbox?',
    'delete_mailbox_desc' => 'This will permanently delete the mailbox and all its emails.',

    // ─── Admin Email Queue ────────────────────────────
    'queue_items'       => 'Queue Items',
    'retry'             => 'Retry',
    'retry_all_failed'  => 'Retry All Failed',
    'clear_sent'        => 'Clear Sent',
    'from'              => 'From',
    'to'                => 'To',
    'subject'           => 'Subject',
    'attempts'          => 'Attempts',
    'retry_all_confirm' => 'Retry All Failed?',
    'retry_all_desc'    => 'This will reset all failed emails to pending status.',
    'clear_sent_confirm' => 'Clear Sent Emails?',
    'clear_sent_desc'   => 'This will remove all sent emails from the queue.',
    'delete_queue'      => 'Delete Queue Item?',

    // ─── Admin Settings ───────────────────────────────
    'general'           => 'General',
    'mail_server'       => 'Mail Server',
    'security'          => 'Security',
    'limits'            => 'Limits',
    'site_name'         => 'Site Name',
    'site_url'          => 'Site URL',
    'timezone_label'    => 'Timezone',
    'system_logo'       => 'System Logo',
    'no_logo'           => 'No logo',
    'upload_logo'       => 'Upload Logo',
    'logo_hint'         => 'PNG, JPG, SVG or WebP. Max 2MB. Recommended: 200x50px',
    'favicon_url'       => 'Favicon URL (optional)',
    'favicon_hint'      => 'URL to a .ico or .png favicon',
    'save_general'      => 'Save General Settings',
    'smtp_config'       => 'SMTP Configuration',
    'smtp_host'         => 'SMTP Host',
    'smtp_port'         => 'SMTP Port',
    'encryption'        => 'Encryption',
    'smtp_username'     => 'SMTP Username',
    'smtp_password'     => 'SMTP Password',
    'keep_current'      => 'Leave empty to keep current',
    'mail_hostname'     => 'Mail Server Hostname',
    'mail_hostname_hint' => 'The hostname that MX records should point to',
    'mx_config'         => 'MX Record Configuration',
    'mx_value'          => 'Required MX Record Value',
    'mx_value_hint'     => 'Users must point their MX records to this value',
    'mx_priority'       => 'MX Priority',
    'save_mail'         => 'Save Mail Settings',
    'allow_registration' => 'Allow Registration',
    'require_verification' => 'Require Email Verification',
    'max_login_attempts' => 'Max Login Attempts',
    'max_login_hint'    => 'Before account lockout',
    'session_timeout'   => 'Session Timeout (minutes)',
    'save_security'     => 'Save Security Settings',
    'max_domains_user'  => 'Max Domains per User',
    'max_mailboxes_domain' => 'Max Mailboxes per Domain',
    'default_quota_mb'  => 'Default Storage Quota (MB)',
    'max_attach_mb'     => 'Max Attachment Size (MB)',
    'max_email_mb'      => 'Max Email Size (MB)',
    'save_limits'       => 'Save Limit Settings',

    // ─── Admin Activity Logs ──────────────────────────
    'total_entries'     => 'total entries',
    'all_users'         => 'All Users',
    'all_actions'       => 'All Actions',
    'date_from'         => 'From',
    'date_to'           => 'To',
    'user_agent'        => 'User Agent',
    'no_logs'           => 'No activity logs found',

    // ─── Admin User Edit ──────────────────────────────
    'edit_user'         => 'Edit User',
    'user_details'      => 'User Details',
    'max_mailboxes_per_domain' => 'Max Mailboxes/Domain',
    'password_keep'     => '(leave empty to keep current)',
    'save_changes'      => 'Save Changes',
    'registered'        => 'Registered',
    'dns'               => 'DNS',
    'email_address'     => 'Email Address',
    'no_domains'        => 'No domains',
    'no_mailboxes'      => 'No mailboxes',

    // ─── Admin System Info ────────────────────────────
    'system_information' => 'System Information',
    'services_ports'    => 'Services & Ports',
    'service'           => 'Service',
    'active_ports'      => 'Active Ports',
    'expected_ports'    => 'Expected Ports',
    'outbound_port25'   => 'Outbound Port 25',
    'smtp_configuration' => 'SMTP Configuration',
    'server_environment' => 'Server Environment',
    'disk_usage'        => 'Disk Usage',
    'php_extensions'    => 'PHP Extensions',
    'database_tables'   => 'Database Tables',
    'cron_logs'         => 'Cron Logs',
    'emails'            => 'Emails',
    'queue_label'       => 'Queue',
    'stopped'           => 'Stopped',
    'open'              => 'Open',
    'not_set_local'     => 'Not set (local delivery)',
    'not_configured'    => 'Not configured',
    'mail_storage'      => 'Mail Storage',
    'ssl_certificate'   => 'SSL Certificate',
    'valid_until'       => 'Valid until',
    'torymail_version'  => 'Torymail Version',
    'install_path'      => 'Install Path',
    'server_os'         => 'Server OS',
    'hostname'          => 'Hostname',
    'server_ip'         => 'Server IP',
    'web_server'        => 'Web Server',
    'php_version'       => 'PHP Version',
    'memory_limit'      => 'Memory Limit',
    'upload_max_size'   => 'Upload Max Size',
    'post_max_size'     => 'Post Max Size',
    'max_execution_time' => 'Max Execution Time',
    'database_label'    => 'Database',
    'used_label'        => 'used',
    'total_label'       => 'total',
    'free_label'        => 'free',
    'table_name'        => 'Table',
    'rows'              => 'Rows',
    'data'              => 'Data',
    'index_col'         => 'Index',
    'cron_log_last5'    => 'Cron Log (Last 5 lines)',
    'imap_fetch_log'    => 'IMAP Fetch Log (Last 5 lines)',
    'no_cron_logs'      => 'No cron logs found',
    'no_fetch_logs'     => 'No fetch logs found',
    'outbound_port25_open' => 'Outbound port 25 is open - direct mail delivery available',
    'outbound_port25_blocked' => 'Outbound port 25 is blocked by hosting provider - need SMTP relay for sending',
    'admin'             => 'Admin',
    'no_activity_short' => 'No activity',
    'date'              => 'Date',
    'adding'            => 'Adding...',
    'logo_max_size'     => 'Logo file must be under 2MB',
    'upload_failed'     => 'Upload failed',

    // ─── User Inbox ───────────────────────────────────
    'all_mailboxes_filter' => 'All Mailboxes',
    'mark_read'         => 'Mark as read',
    'mark_unread'       => 'Mark as unread',
    'move_to'           => 'Move to',
    'no_emails'         => 'No emails in inbox',
    'no_subject'        => '(No subject)',
    'search_placeholder' => 'Search',

    // ─── User Compose ─────────────────────────────────
    'compose_title'     => 'Compose — Torymail',
    'new_email'         => 'New Email',
    'edit_draft'        => 'Edit Draft',
    'to_placeholder'    => 'recipient@example.com',
    'cc'                => 'Cc',
    'bcc'               => 'Bcc',
    'subject_placeholder' => 'Email subject',
    'bold'              => 'Bold',
    'italic'            => 'Italic',
    'underline'         => 'Underline',
    'bullet_list'       => 'Bullet list',
    'number_list'       => 'Numbered list',
    'insert_link'       => 'Insert link',
    'insert_image'      => 'Insert image',
    'clear_format'      => 'Clear formatting',
    'drop_files'        => 'Drop files here or click to attach',
    'save_draft'        => 'Save Draft',
    'normal_priority'   => 'Normal Priority',
    'high_priority'     => 'High Priority',
    'low_priority'      => 'Low Priority',
    'no_mailbox_warning' => 'No active mailboxes — please set up a mailbox first',
    'compose_hint'      => 'Write your email here...',
    'send_failed'       => 'Failed to send email.',
    'save_failed'       => 'Failed to save email.',
    'network_error'     => 'A network error occurred.',

    // ─── User Read ────────────────────────────────────
    'read_email'        => 'Read Email',
    'report_spam'       => 'Report spam',
    'move_to_folder'    => 'Move to folder',
    'no_labels'         => 'No labels',
    'sent_by'           => 'Sent by:',
    'attachments'       => 'Attachment(s)',
    'delete_email'      => 'Delete this email?',
    'delete_email_desc' => 'It will be moved to trash.',
    'error_occurred'    => 'An error occurred.',
    'earlier_messages'  => 'earlier message(s) in this thread',

    // ─── User Settings ────────────────────────────────
    'settings_title'    => 'Settings — Torymail',
    'account_settings'  => 'Account settings',
    'profile'           => 'Profile',
    'signature'         => 'Signature',
    'auto_reply'        => 'Auto-reply',
    'display'           => 'Display',
    'username'          => 'Username',
    'username_note'     => 'Username cannot be changed.',
    'your_fullname'     => 'Your full name',
    'avatar_url'        => 'Avatar URL',
    'avatar_hint'       => 'Enter a URL to your avatar image.',
    'save_profile'      => 'Save Profile',
    'change_password'   => 'Change Password',
    'current_password'  => 'Current Password',
    'new_password_label' => 'New Password',
    'confirm_new_password' => 'Confirm New Password',
    'update_password'   => 'Update Password',
    'two_factor'        => 'Two-Factor Authentication',
    '2fa_enabled'       => '2FA is enabled',
    '2fa_enabled_desc'  => 'Your account is protected with two-factor authentication.',
    'disable_2fa'       => 'Disable 2FA',
    '2fa_disabled'      => '2FA is not enabled',
    '2fa_disabled_desc' => 'Add an extra layer of security to your account.',
    'enable_2fa'        => 'Enable 2FA',
    'select_mailbox'    => 'Select Mailbox',
    'email_signature'   => 'Email Signature (HTML)',
    'save_signature'    => 'Save Signature',
    'no_mailbox_msg'    => 'No active mailboxes. Create a mailbox first.',
    'enable_auto_reply' => 'Enable Auto-reply',
    'auto_reply_subject' => "I'm currently out of office",
    'auto_reply_msg'    => 'Thank you for your email. I am currently out of the office...',
    'save_auto_reply'   => 'Save Auto-reply',
    'emails_per_page'   => 'Emails Per Page',
    'default_mailbox'   => 'Default Mailbox',
    'no_default'        => 'No default',
    'save_display'      => 'Save Display Settings',
    'settings_saved'    => 'Settings saved!',
    'settings_failed'   => 'Failed to save settings.',

    // ─── User Contacts ────────────────────────────────
    'add_contact'       => 'Add Contact',
    'edit_contact'      => 'Edit Contact',
    'search_contacts'   => 'Search contacts...',
    'all_groups'        => 'All Groups',
    'company'           => 'Company',
    'group'             => 'Group',
    'phone'             => 'Phone',
    'notes'             => 'Notes',
    'save_contact'      => 'Save Contact',
    'delete_contact'    => 'Delete contact?',
    'delete_contact_desc' => 'This action cannot be undone.',
    'contact_saved'     => 'Contact saved!',
    'contact_save_fail' => 'Failed to save contact.',
    'contact_deleted'   => 'Contact deleted.',
    'contact_delete_fail' => 'Failed to delete contact.',
    'no_contacts'       => 'No contacts found',

    // ─── User Domains ─────────────────────────────────
    'manage_domains'    => 'Manage your email domains',
    'domain_placeholder' => 'example.com',
    'domain_hint'       => 'Enter your domain name without http:// or www.',
    'domain_dns_note'   => 'After adding the domain, you will need to configure DNS records.',
    'dns_setup'         => 'DNS Setup',
    'dns_instructions'  => 'Add the following DNS records to your domain\'s DNS settings.',
    'dns_propagation'   => 'Changes may take up to 48 hours to propagate.',
    'mx_record'         => 'MX Record',
    'spf_record'        => 'SPF Record',
    'dkim_record'       => 'DKIM Record',
    'dmarc_record'      => 'DMARC Record',
    'type'              => 'Type',
    'host'              => 'Host',
    'value'             => 'Value',
    'priority'          => 'Priority',
    'txt_verification'  => 'TXT Verification',
    'verify_dns_records' => 'Verify DNS Records',
    'domain_added'      => 'Domain added! Please configure DNS records.',
    'domain_add_fail'   => 'Failed to add domain.',
    'dns_complete'      => 'DNS verification complete!',
    'dns_failed'        => 'DNS verification failed. Please check your records.',
    'delete_domain_user' => 'Delete domain?',
    'delete_domain_user_desc' => 'All mailboxes under this domain will also be removed.',
    'domain_deleted'    => 'Domain deleted.',
    'domain_delete_fail' => 'Failed to delete domain.',
    'no_domains_user'   => 'No domains configured',
    'no_domains_hint'   => 'Add a domain to start receiving and sending emails.',

    // ─── User Mailboxes ───────────────────────────────
    'manage_mailboxes'  => 'Manage your mailboxes',
    'add_mailbox'       => 'Add Mailbox',
    'edit_mailbox'      => 'Edit Mailbox',
    'display_name'      => 'Display Name',
    'usage_quota'       => 'Usage / Quota',
    'select_domain'     => 'Select domain',
    'no_verified_domains' => 'No verified domains. Add a domain first.',
    'email_username'    => 'username',
    'mailbox_password'  => 'Mailbox password',
    'password_min_hint' => 'Minimum 8 characters.',
    'quota_mb'          => 'Quota (MB)',
    'quota_hint'        => 'Set to 0 for unlimited. Default is 1024 MB (1 GB).',
    'save_mailbox'      => 'Save Mailbox',
    'password_keep_hint' => 'Leave blank to keep current password.',
    'delete_mailbox_user' => 'Delete mailbox?',
    'delete_mailbox_user_desc' => 'All emails in this mailbox will be permanently deleted.',
    'mailbox_saved'     => 'Mailbox saved!',
    'mailbox_save_fail' => 'Failed to save mailbox.',
    'mailbox_deleted'   => 'Mailbox deleted.',
    'mailbox_delete_fail' => 'Failed to delete mailbox.',
    'no_mailboxes_user' => 'No mailboxes configured',
    'no_mailboxes_hint' => 'Create a mailbox to start sending and receiving emails.',
    'need_domain_first' => 'You need to add and verify a domain first.',

    // ─── User Templates ───────────────────────────────
    'email_templates'   => 'Email Templates',
    'add_template'      => 'Add Template',
    'edit_template'     => 'Edit Template',
    'template_name'     => 'Template Name',
    'template_name_placeholder' => 'e.g., Welcome Email',
    'subject_placeholder_tpl' => 'Email subject line',
    'body_html'         => 'Body (HTML)',
    'save_template'     => 'Save Template',
    'delete_template'   => 'Delete this template?',
    'delete_template_desc' => 'This action cannot be undone.',
    'template_saved'    => 'Template saved!',
    'template_save_fail' => 'Failed to save template.',
    'template_deleted'  => 'Template deleted.',
    'template_delete_fail' => 'Failed to delete template.',
    'no_templates'      => 'No templates yet',
    'no_templates_hint' => 'Create reusable email templates to save time composing emails.',
    'last_updated'      => 'Last Updated',

    // ─── User Filters ─────────────────────────────────
    'email_filters'     => 'Email Filters',
    'add_filter'        => 'Add Filter',
    'edit_filter'       => 'Edit Filter',
    'filter_name'       => 'Filter Name',
    'filter_name_placeholder' => 'e.g., Move newsletters',
    'condition'         => 'Condition',
    'when'              => 'When',
    'then'              => 'Then',
    'from_contains'     => 'From contains',
    'from_equals'       => 'From equals',
    'to_contains'       => 'To contains',
    'to_equals'         => 'To equals',
    'subject_contains'  => 'Subject contains',
    'subject_equals'    => 'Subject equals',
    'body_contains'     => 'Body contains',
    'has_attachment'     => 'Has attachment',
    'move_to_folder_action' => 'Move to folder',
    'add_label'         => 'Add label',
    'mark_as_read'      => 'Mark as read',
    'mark_as_starred'   => 'Mark as starred',
    'forward_to'        => 'Forward to',
    'folder'            => 'Folder',
    'label'             => 'Label',
    'priority_order'    => 'Priority Order (lower = runs first)',
    'save_filter'       => 'Save Filter',
    'delete_filter'     => 'Delete this filter?',
    'delete_filter_desc' => 'This action cannot be undone.',
    'filter_saved'      => 'Filter saved!',
    'filter_save_fail'  => 'Failed to save filter.',
    'filter_deleted'    => 'Filter deleted.',
    'filter_delete_fail' => 'Failed to delete filter.',
    'no_filters'        => 'No filters configured',
    'no_filters_hint'   => 'Create filters to automatically organize incoming emails.',

    // ─── User Labels ──────────────────────────────────
    'manage_labels'     => 'Manage email labels',
    'add_label_btn'     => 'Add Label',
    'edit_label'        => 'Edit Label',
    'label_name'        => 'Label Name',
    'label_name_placeholder' => 'e.g., Important',
    'color'             => 'Color',
    'save_label'        => 'Save Label',
    'delete_label'      => 'Delete label?',
    'delete_label_desc' => 'The label will be removed from all emails.',
    'label_saved'       => 'Label saved!',
    'label_save_fail'   => 'Failed to save label.',
    'label_deleted'     => 'Label deleted.',
    'label_delete_fail' => 'Failed to delete label.',
    'emails_count'      => 'email(s)',

    // ─── Additional Keys ─────────────────────────────
    'select_emails_warning' => 'Please select at least one email.',
    'delete_emails_confirm' => 'Delete emails?',
    'delete_emails_desc'    => 'Selected emails will be moved to trash.',
    'email_sent'            => 'Email sent!',
    'draft_saved'           => 'Draft saved!',
    'enter_domain_warning'  => 'Please enter a domain name.',
    'adding'                => 'Adding...',
    'no_labels_yet'         => 'No labels yet',
    'no_labels_hint'        => 'Create labels to organize your emails by category.',
    'message'               => 'Message',

    // ─── Auth messages ────────────────────────────────
    'login_success'     => 'Login successful! Redirecting...',
    'register_success'  => 'Registration successful! Redirecting to login...',

    // ─── Language ────────────────────────────────────────
    'default_language'      => 'Default Language',
    'default_language_hint' => 'Default display language for new users.',

    // ─── Footer ───────────────────────────────────────
    'footer_system'     => 'Email Management System',
];
