<?php
/**
 * Vietnamese Language File — Torymail
 */
return [

    // ─── Common ───────────────────────────────────────
    'save'              => 'Lưu',
    'cancel'            => 'Hủy',
    'delete'            => 'Xóa',
    'edit'              => 'Sửa',
    'add'               => 'Thêm',
    'close'             => 'Đóng',
    'send'              => 'Gửi',
    'reply'             => 'Trả lời',
    'reply_all'         => 'Trả lời tất cả',
    'forward'           => 'Chuyển tiếp',
    'download'          => 'Tải xuống',
    'create'            => 'Tạo',
    'update'            => 'Cập nhật',
    'remove'            => 'Xóa',
    'enable'            => 'Bật',
    'disable'           => 'Tắt',
    'reset'             => 'Đặt lại',
    'filter'            => 'Lọc',
    'verify'            => 'Xác minh',
    'activate'          => 'Kích hoạt',
    'suspend'           => 'Tạm ngưng',
    'archive'           => 'Lưu trữ',
    'move'              => 'Di chuyển',
    'refresh'           => 'Làm mới',
    'discard'           => 'Hủy bỏ',
    'loading'           => 'Đang tải...',
    'processing'        => 'Đang xử lý...',
    'saving'            => 'Đang lưu...',
    'sending'           => 'Đang gửi...',
    'creating'          => 'Đang tạo...',
    'resetting'         => 'Đang đặt lại...',
    'search'            => 'Tìm kiếm',
    'actions'           => 'Thao tác',
    'status'            => 'Trạng thái',
    'created'           => 'Ngày tạo',
    'yes'               => 'Có',
    'no'                => 'Không',
    'all'               => 'Tất cả',
    'none'              => 'Không có',
    'home'              => 'Trang chủ',
    'back'              => 'Quay lại',
    'view_details'      => 'Xem chi tiết',
    'server_error'      => 'Lỗi kết nối máy chủ',
    'confirm'           => 'Xác nhận',
    'proceed'           => 'Đồng ý, tiếp tục',
    'never'             => 'Chưa bao giờ',
    'no_data'           => 'Không tìm thấy dữ liệu',
    'required'          => 'Bắt buộc',
    'optional'          => 'Tùy chọn',
    'success'           => 'Thành công',
    'error'             => 'Lỗi',
    'warning'           => 'Cảnh báo',
    'done'              => 'Hoàn tất!',
    'language'          => 'Ngôn ngữ',

    // ─── Status badges ────────────────────────────────
    'active'            => 'Hoạt động',
    'inactive'          => 'Không hoạt động',
    'disabled'          => 'Đã tắt',
    'banned'            => 'Bị cấm',
    'suspended'         => 'Tạm ngưng',
    'pending'           => 'Chờ xử lý',
    'sending_status'    => 'Đang gửi',
    'sent'              => 'Đã gửi',
    'failed'            => 'Thất bại',
    'verified'          => 'Đã xác minh',
    'running'           => 'Đang chạy',
    'blocked'           => 'Bị chặn',

    // ─── Roles ────────────────────────────────────────
    'role_admin'        => 'Quản trị',
    'role_user'         => 'Người dùng',

    // ─── Auth ─────────────────────────────────────────
    'login'             => 'Đăng nhập',
    'register'          => 'Đăng ký',
    'logout'            => 'Đăng xuất',
    'login_title'       => 'Đăng nhập — Torymail',
    'login_subtitle'    => 'Đăng nhập vào hệ thống email Torymail',
    'login_welcome'     => 'Chào mừng trở lại!',
    'login_desc'        => 'Đăng nhập để tiếp tục sử dụng Torymail.',
    'email'             => 'Email',
    'email_placeholder' => 'Nhập email',
    'password'          => 'Mật khẩu',
    'password_placeholder' => 'Nhập mật khẩu',
    'remember_me'       => 'Ghi nhớ đăng nhập',
    'forgot_password'   => 'Quên mật khẩu?',
    'no_account'        => 'Chưa có tài khoản?',
    'register_now'      => 'Đăng ký ngay',
    'register_title'    => 'Đăng ký — Torymail',
    'register_subtitle' => 'Tạo tài khoản mới',
    'register_desc'     => 'Tạo tài khoản miễn phí ngay hôm nay.',
    'fullname'          => 'Họ và tên',
    'fullname_placeholder' => 'Nguyễn Văn A',
    'email_register_placeholder' => 'you@example.com',
    'password_min'      => 'Tối thiểu 8 ký tự',
    'confirm_password'  => 'Xác nhận mật khẩu',
    'confirm_password_placeholder' => 'Nhập lại mật khẩu',
    'has_account'       => 'Đã có tài khoản?',
    'forgot_title'      => 'Quên mật khẩu — Torymail',
    'forgot_subtitle'   => 'Khôi phục mật khẩu',
    'forgot_desc'       => 'Nhập email để nhận link khôi phục mật khẩu.',
    'forgot_email_placeholder' => 'Nhập email đăng ký',
    'send_recovery'     => 'Gửi link khôi phục',
    'remember_password' => 'Nhớ mật khẩu rồi?',
    'system_tagline'    => 'Hệ thống email chuyên nghiệp',

    // ─── Admin Sidebar ────────────────────────────────
    'menu'              => 'Menu',
    'dashboard'         => 'Bảng điều khiển',
    'users'             => 'Người dùng',
    'domains'           => 'Tên miền',
    'mailboxes'         => 'Hộp thư',
    'email_queue'       => 'Hàng đợi Email',
    'activity_logs'     => 'Nhật ký hoạt động',
    'settings'          => 'Cài đặt',
    'system_info'       => 'Thông tin hệ thống',

    // ─── User Sidebar ─────────────────────────────────
    'compose'           => 'Soạn thư',
    'mailbox'           => 'Hộp thư',
    'inbox'             => 'Hộp thư đến',
    'starred'           => 'Gắn sao',
    'drafts'            => 'Nháp',
    'spam'              => 'Thư rác',
    'trash'             => 'Thùng rác',
    'management'        => 'Quản lý',
    'contacts'          => 'Danh bạ',
    'templates'         => 'Mẫu email',
    'filters'           => 'Bộ lọc',
    'labels'            => 'Nhãn',

    // ─── Admin Dashboard ──────────────────────────────
    'total_users'       => 'Tổng người dùng',
    'active_domains'    => 'Tên miền hoạt động',
    'active_mailboxes'  => 'Hộp thư hoạt động',
    'emails_today'      => 'Email hôm nay',
    'queue_pending'     => 'Đang chờ gửi',
    'total_storage'     => 'Tổng dung lượng',
    'emails_last_30'    => 'Email — 30 ngày qua',
    'received'          => 'Nhận',
    'recent_activity'   => 'Hoạt động gần đây',
    'no_activity'       => 'Chưa có hoạt động nào',
    'time'              => 'Thời gian',
    'user'              => 'Người dùng',
    'action'            => 'Hành động',
    'details'           => 'Chi tiết',
    'ip'                => 'IP',

    // ─── Admin Users ──────────────────────────────────
    'all_users'         => 'Tất cả người dùng',
    'add_user'          => 'Thêm người dùng',
    'name'              => 'Tên',
    'role'              => 'Vai trò',
    'storage'           => 'Dung lượng',
    'last_activity'     => 'Hoạt động cuối',
    'max_domains'       => 'Số tên miền tối đa',
    'storage_quota_mb'  => 'Dung lượng (MB)',
    'create_user'       => 'Tạo người dùng',
    'ban'               => 'Cấm',
    'unban'             => 'Bỏ cấm',
    'ban_confirm'       => 'Cấm người dùng này?',
    'unban_confirm'     => 'Bỏ cấm người dùng này?',
    'ban_desc'          => 'Thao tác này sẽ thay đổi quyền truy cập của người dùng.',
    'delete_user'       => 'Xóa người dùng?',
    'delete_user_desc'  => 'Thao tác không thể hoàn tác. Tất cả dữ liệu người dùng sẽ bị xóa vĩnh viễn.',

    // ─── Admin Domains ────────────────────────────────
    'all_domains'       => 'Tất cả tên miền',
    'add_domain'        => 'Thêm tên miền',
    'domain'            => 'Tên miền',
    'domain_name'       => 'Tên miền',
    'owner'             => 'Chủ sở hữu',
    'select_user'       => '-- Chọn người dùng --',
    'auto_verify'       => 'Tự động xác minh (bỏ qua kiểm tra DNS)',
    'verify_dns'        => 'Xác minh DNS',
    'suspend_domain'    => 'Tạm ngưng tên miền này?',
    'suspend_domain_desc' => 'Tất cả hộp thư thuộc tên miền này sẽ bị ảnh hưởng.',
    'activate_domain'   => 'Kích hoạt tên miền này?',
    'delete_domain'     => 'Xóa tên miền?',
    'delete_domain_desc' => 'Tên miền và tất cả hộp thư sẽ bị xóa vĩnh viễn.',
    'shared'            => 'Dùng chung',
    'shared_domain'     => 'Tên miền dùng chung',
    'shared_domain_desc' => 'Tên miền dùng chung cho phép tất cả người dùng tạo hộp thư mà không cần thêm tên miền riêng.',
    'set_shared'        => 'Đặt làm dùng chung',
    'unset_shared'      => 'Bỏ dùng chung',
    'system'            => 'Hệ thống',
    'managed_by_admin'  => 'Quản lý bởi admin',

    // ─── Admin Mailboxes ──────────────────────────────
    'all_mailboxes'     => 'Tất cả hộp thư',
    'used_quota'        => 'Đã dùng / Hạn mức',
    'reset_password'    => 'Đặt lại mật khẩu',
    'reset_password_for' => 'Đặt lại mật khẩu cho:',
    'new_password'      => 'Mật khẩu mới',
    'disable_mailbox'   => 'Tắt hộp thư này?',
    'enable_mailbox'    => 'Bật hộp thư này?',
    'delete_mailbox'    => 'Xóa hộp thư?',
    'delete_mailbox_desc' => 'Hộp thư và tất cả email sẽ bị xóa vĩnh viễn.',

    // ─── Admin Email Queue ────────────────────────────
    'queue_items'       => 'Danh sách hàng đợi',
    'retry'             => 'Thử lại',
    'retry_all_failed'  => 'Thử lại tất cả thất bại',
    'clear_sent'        => 'Xóa đã gửi',
    'from'              => 'Từ',
    'to'                => 'Đến',
    'subject'           => 'Tiêu đề',
    'attempts'          => 'Lần thử',
    'retry_all_confirm' => 'Thử lại tất cả thất bại?',
    'retry_all_desc'    => 'Tất cả email thất bại sẽ được chuyển về trạng thái chờ.',
    'clear_sent_confirm' => 'Xóa email đã gửi?',
    'clear_sent_desc'   => 'Tất cả email đã gửi sẽ bị xóa khỏi hàng đợi.',
    'delete_queue'      => 'Xóa mục hàng đợi?',

    // ─── Admin Settings ───────────────────────────────
    'general'           => 'Chung',
    'mail_server'       => 'Máy chủ Email',
    'security'          => 'Bảo mật',
    'limits'            => 'Giới hạn',
    'site_name'         => 'Tên trang web',
    'site_url'          => 'URL trang web',
    'timezone_label'    => 'Múi giờ',
    'system_logo'       => 'Logo hệ thống',
    'no_logo'           => 'Chưa có logo',
    'upload_logo'       => 'Tải lên logo',
    'logo_hint'         => 'PNG, JPG, SVG hoặc WebP. Tối đa 2MB. Khuyến nghị: 200x50px',
    'favicon_url'       => 'URL Favicon (tùy chọn)',
    'favicon_hint'      => 'URL đến file .ico hoặc .png favicon',
    'save_general'      => 'Lưu cài đặt chung',
    'smtp_config'       => 'Cấu hình SMTP',
    'smtp_host'         => 'Máy chủ SMTP',
    'smtp_port'         => 'Cổng SMTP',
    'encryption'        => 'Mã hóa',
    'smtp_username'     => 'Tên đăng nhập SMTP',
    'smtp_password'     => 'Mật khẩu SMTP',
    'keep_current'      => 'Để trống để giữ nguyên',
    'mail_hostname'     => 'Hostname máy chủ Email',
    'mail_hostname_hint' => 'Hostname mà bản ghi MX cần trỏ đến',
    'mx_config'         => 'Cấu hình bản ghi MX',
    'mx_value'          => 'Giá trị bản ghi MX',
    'mx_value_hint'     => 'Người dùng cần trỏ bản ghi MX đến giá trị này',
    'mx_priority'       => 'Độ ưu tiên MX',
    'save_mail'         => 'Lưu cài đặt Email',
    'allow_registration' => 'Cho phép đăng ký',
    'require_verification' => 'Yêu cầu xác minh Email',
    'max_login_attempts' => 'Số lần đăng nhập tối đa',
    'max_login_hint'    => 'Trước khi khóa tài khoản',
    'session_timeout'   => 'Thời gian phiên (phút)',
    'save_security'     => 'Lưu cài đặt bảo mật',
    'max_domains_user'  => 'Số tên miền tối đa/người dùng',
    'max_mailboxes_domain' => 'Số hộp thư tối đa/tên miền',
    'default_quota_mb'  => 'Dung lượng mặc định (MB)',
    'max_attach_mb'     => 'Kích thước đính kèm tối đa (MB)',
    'max_email_mb'      => 'Kích thước email tối đa (MB)',
    'save_limits'       => 'Lưu giới hạn',

    // ─── Admin Activity Logs ──────────────────────────
    'total_entries'     => 'tổng số bản ghi',
    'all_actions'       => 'Tất cả hành động',
    'date_from'         => 'Từ ngày',
    'date_to'           => 'Đến ngày',
    'user_agent'        => 'Trình duyệt',
    'no_logs'           => 'Không tìm thấy nhật ký hoạt động',

    // ─── Admin User Edit ──────────────────────────────
    'edit_user'         => 'Sửa người dùng',
    'user_details'      => 'Thông tin người dùng',
    'max_mailboxes_per_domain' => 'Số hộp thư tối đa/tên miền',
    'password_keep'     => '(để trống để giữ nguyên)',
    'save_changes'      => 'Lưu thay đổi',
    'registered'        => 'Ngày đăng ký',
    'dns'               => 'DNS',
    'email_address'     => 'Địa chỉ Email',
    'no_domains'        => 'Chưa có tên miền',
    'no_mailboxes'      => 'Chưa có hộp thư',

    // ─── Admin System Info ────────────────────────────
    'system_information' => 'Thông tin hệ thống',
    'services_ports'    => 'Dịch vụ & Cổng',
    'service'           => 'Dịch vụ',
    'active_ports'      => 'Cổng đang hoạt động',
    'expected_ports'    => 'Cổng mong đợi',
    'outbound_port25'   => 'Cổng 25 gửi đi',
    'smtp_configuration' => 'Cấu hình SMTP',
    'server_environment' => 'Môi trường máy chủ',
    'disk_usage'        => 'Dung lượng ổ đĩa',
    'php_extensions'    => 'PHP Extensions',
    'database_tables'   => 'Bảng cơ sở dữ liệu',
    'cron_logs'         => 'Nhật ký Cron',
    'emails'            => 'Email',
    'queue_label'       => 'Hàng đợi',
    'stopped'           => 'Đã dừng',
    'open'              => 'Mở',
    'not_set_local'     => 'Chưa đặt (gửi nội bộ)',
    'not_configured'    => 'Chưa cấu hình',
    'mail_storage'      => 'Lưu trữ Email',
    'ssl_certificate'   => 'Chứng chỉ SSL',
    'valid_until'       => 'Hợp lệ đến',
    'torymail_version'  => 'Phiên bản Torymail',
    'install_path'      => 'Đường dẫn cài đặt',
    'server_os'         => 'Hệ điều hành',
    'hostname'          => 'Tên máy chủ',
    'server_ip'         => 'IP máy chủ',
    'web_server'        => 'Máy chủ Web',
    'php_version'       => 'Phiên bản PHP',
    'memory_limit'      => 'Giới hạn bộ nhớ',
    'upload_max_size'   => 'Kích thước tải lên tối đa',
    'post_max_size'     => 'Kích thước POST tối đa',
    'max_execution_time' => 'Thời gian thực thi tối đa',
    'database_label'    => 'Cơ sở dữ liệu',
    'used_label'        => 'đã dùng',
    'total_label'       => 'tổng',
    'free_label'        => 'trống',
    'table_name'        => 'Bảng',
    'rows'              => 'Dòng',
    'data'              => 'Dữ liệu',
    'index_col'         => 'Chỉ mục',
    'cron_log_last5'    => 'Nhật ký Cron (5 dòng cuối)',
    'imap_fetch_log'    => 'Nhật ký IMAP Fetch (5 dòng cuối)',
    'no_cron_logs'      => 'Không tìm thấy nhật ký cron',
    'no_fetch_logs'     => 'Không tìm thấy nhật ký fetch',
    'outbound_port25_open' => 'Cổng 25 gửi đi mở - có thể gửi email trực tiếp',
    'outbound_port25_blocked' => 'Cổng 25 gửi đi bị chặn bởi nhà cung cấp - cần SMTP relay để gửi',
    'admin'             => 'Quản trị',
    'no_activity_short' => 'Không có hoạt động',
    'date'              => 'Ngày',
    'adding'            => 'Đang thêm...',
    'logo_max_size'     => 'File logo phải nhỏ hơn 2MB',
    'upload_failed'     => 'Tải lên thất bại',

    // ─── User Inbox ───────────────────────────────────
    'all_mailboxes_filter' => 'Tất cả hộp thư',
    'mark_read'         => 'Đánh dấu đã đọc',
    'mark_unread'       => 'Đánh dấu chưa đọc',
    'move_to'           => 'Di chuyển đến',
    'no_emails'         => 'Không có email trong hộp thư',
    'no_subject'        => '(Không có tiêu đề)',
    'search_placeholder' => 'Tìm kiếm',

    // ─── User Compose ─────────────────────────────────
    'compose_title'     => 'Soạn thư — Torymail',
    'new_email'         => 'Email mới',
    'edit_draft'        => 'Sửa nháp',
    'to_placeholder'    => 'nguoinhan@example.com',
    'cc'                => 'Cc',
    'bcc'               => 'Bcc',
    'subject_placeholder' => 'Tiêu đề email',
    'bold'              => 'In đậm',
    'italic'            => 'In nghiêng',
    'underline'         => 'Gạch chân',
    'bullet_list'       => 'Danh sách dấu đầu dòng',
    'number_list'       => 'Danh sách đánh số',
    'insert_link'       => 'Chèn liên kết',
    'insert_image'      => 'Chèn hình ảnh',
    'clear_format'      => 'Xóa định dạng',
    'drop_files'        => 'Kéo thả file vào đây hoặc nhấn để đính kèm',
    'save_draft'        => 'Lưu nháp',
    'normal_priority'   => 'Ưu tiên bình thường',
    'high_priority'     => 'Ưu tiên cao',
    'low_priority'      => 'Ưu tiên thấp',
    'no_mailbox_warning' => 'Chưa có hộp thư — vui lòng tạo hộp thư trước',
    'compose_hint'      => 'Viết email của bạn ở đây...',
    'send_failed'       => 'Gửi email thất bại.',
    'save_failed'       => 'Lưu email thất bại.',
    'network_error'     => 'Lỗi kết nối mạng.',

    // ─── User Read ────────────────────────────────────
    'read_email'        => 'Đọc Email',
    'report_spam'       => 'Báo thư rác',
    'move_to_folder'    => 'Di chuyển đến thư mục',
    'no_labels'         => 'Không có nhãn',
    'sent_by'           => 'Gửi bởi:',
    'attachments'       => 'Tệp đính kèm',
    'delete_email'      => 'Xóa email này?',
    'delete_email_desc' => 'Email sẽ được chuyển vào thùng rác.',
    'error_occurred'    => 'Đã xảy ra lỗi.',
    'earlier_messages'  => 'tin nhắn trước đó trong chuỗi',

    // ─── User Settings ────────────────────────────────
    'settings_title'    => 'Cài đặt — Torymail',
    'account_settings'  => 'Cài đặt tài khoản',
    'profile'           => 'Hồ sơ',
    'signature'         => 'Chữ ký',
    'auto_reply'        => 'Tự động trả lời',
    'display'           => 'Hiển thị',
    'username'          => 'Tên đăng nhập',
    'username_note'     => 'Tên đăng nhập không thể thay đổi.',
    'your_fullname'     => 'Họ và tên của bạn',
    'avatar_url'        => 'URL ảnh đại diện',
    'avatar_hint'       => 'Nhập URL đến ảnh đại diện của bạn.',
    'save_profile'      => 'Lưu hồ sơ',
    'change_password'   => 'Đổi mật khẩu',
    'current_password'  => 'Mật khẩu hiện tại',
    'new_password_label' => 'Mật khẩu mới',
    'confirm_new_password' => 'Xác nhận mật khẩu mới',
    'update_password'   => 'Cập nhật mật khẩu',
    'two_factor'        => 'Xác thực hai lớp',
    '2fa_enabled'       => '2FA đã bật',
    '2fa_enabled_desc'  => 'Tài khoản của bạn đang được bảo vệ bằng xác thực hai lớp.',
    'disable_2fa'       => 'Tắt 2FA',
    '2fa_disabled'      => '2FA chưa bật',
    '2fa_disabled_desc' => 'Thêm một lớp bảo mật cho tài khoản của bạn.',
    'enable_2fa'        => 'Bật 2FA',
    'select_mailbox'    => 'Chọn hộp thư',
    'email_signature'   => 'Chữ ký Email (HTML)',
    'save_signature'    => 'Lưu chữ ký',
    'no_mailbox_msg'    => 'Chưa có hộp thư. Vui lòng tạo hộp thư trước.',
    'enable_auto_reply' => 'Bật tự động trả lời',
    'auto_reply_subject' => 'Tôi hiện không có mặt tại văn phòng',
    'auto_reply_msg'    => 'Cảm ơn bạn đã gửi email. Tôi hiện không có mặt tại văn phòng...',
    'save_auto_reply'   => 'Lưu tự động trả lời',
    'emails_per_page'   => 'Số email mỗi trang',
    'default_mailbox'   => 'Hộp thư mặc định',
    'no_default'        => 'Không có mặc định',
    'save_display'      => 'Lưu cài đặt hiển thị',
    'settings_saved'    => 'Đã lưu cài đặt!',
    'settings_failed'   => 'Lưu cài đặt thất bại.',

    // ─── User Contacts ────────────────────────────────
    'add_contact'       => 'Thêm liên hệ',
    'edit_contact'      => 'Sửa liên hệ',
    'search_contacts'   => 'Tìm kiếm liên hệ...',
    'all_groups'        => 'Tất cả nhóm',
    'company'           => 'Công ty',
    'group'             => 'Nhóm',
    'phone'             => 'Điện thoại',
    'notes'             => 'Ghi chú',
    'save_contact'      => 'Lưu liên hệ',
    'delete_contact'    => 'Xóa liên hệ?',
    'delete_contact_desc' => 'Thao tác này không thể hoàn tác.',
    'contact_saved'     => 'Đã lưu liên hệ!',
    'contact_save_fail' => 'Lưu liên hệ thất bại.',
    'contact_deleted'   => 'Đã xóa liên hệ.',
    'contact_delete_fail' => 'Xóa liên hệ thất bại.',
    'no_contacts'       => 'Không tìm thấy liên hệ',

    // ─── User Domains ─────────────────────────────────
    'manage_domains'    => 'Quản lý tên miền email',
    'domain_placeholder' => 'example.com',
    'domain_hint'       => 'Nhập tên miền không có http:// hoặc www.',
    'domain_dns_note'   => 'Sau khi thêm tên miền, bạn cần cấu hình bản ghi DNS.',
    'dns_setup'         => 'Cài đặt DNS',
    'dns_instructions'  => 'Thêm các bản ghi DNS sau vào cài đặt DNS của tên miền.',
    'dns_propagation'   => 'Thay đổi có thể mất đến 48 giờ để cập nhật.',
    'mx_record'         => 'Bản ghi MX',
    'spf_record'        => 'Bản ghi SPF',
    'dkim_record'       => 'Bản ghi DKIM',
    'dmarc_record'      => 'Bản ghi DMARC',
    'type'              => 'Loại',
    'host'              => 'Host',
    'value'             => 'Giá trị',
    'priority'          => 'Ưu tiên',
    'txt_verification'  => 'Xác minh TXT',
    'verify_dns_records' => 'Xác minh bản ghi DNS',
    'domain_added'      => 'Đã thêm tên miền! Vui lòng cấu hình bản ghi DNS.',
    'domain_add_fail'   => 'Thêm tên miền thất bại.',
    'dns_complete'      => 'Xác minh DNS hoàn tất!',
    'dns_failed'        => 'Xác minh DNS thất bại. Vui lòng kiểm tra lại bản ghi.',
    'delete_domain_user' => 'Xóa tên miền?',
    'delete_domain_user_desc' => 'Tất cả hộp thư thuộc tên miền này cũng sẽ bị xóa.',
    'domain_deleted'    => 'Đã xóa tên miền.',
    'domain_delete_fail' => 'Xóa tên miền thất bại.',
    'no_domains_user'   => 'Chưa có tên miền nào',
    'no_domains_hint'   => 'Thêm tên miền để bắt đầu nhận và gửi email.',

    // ─── User Mailboxes ───────────────────────────────
    'manage_mailboxes'  => 'Quản lý hộp thư',
    'add_mailbox'       => 'Thêm hộp thư',
    'edit_mailbox'      => 'Sửa hộp thư',
    'display_name'      => 'Tên hiển thị',
    'usage_quota'       => 'Đã dùng / Hạn mức',
    'select_domain'     => 'Chọn tên miền',
    'no_verified_domains' => 'Chưa có tên miền đã xác minh. Thêm tên miền trước.',
    'email_username'    => 'tendangnhap',
    'mailbox_password'  => 'Mật khẩu hộp thư',
    'password_min_hint' => 'Tối thiểu 8 ký tự.',
    'quota_mb'          => 'Hạn mức (MB)',
    'quota_hint'        => 'Đặt 0 cho không giới hạn. Mặc định 1024 MB (1 GB).',
    'save_mailbox'      => 'Lưu hộp thư',
    'password_keep_hint' => 'Để trống để giữ nguyên mật khẩu.',
    'delete_mailbox_user' => 'Xóa hộp thư?',
    'delete_mailbox_user_desc' => 'Tất cả email trong hộp thư này sẽ bị xóa vĩnh viễn.',
    'mailbox_saved'     => 'Đã lưu hộp thư!',
    'mailbox_save_fail' => 'Lưu hộp thư thất bại.',
    'mailbox_deleted'   => 'Đã xóa hộp thư.',
    'mailbox_delete_fail' => 'Xóa hộp thư thất bại.',
    'no_mailboxes_user' => 'Chưa có hộp thư nào',
    'no_mailboxes_hint' => 'Tạo hộp thư để bắt đầu gửi và nhận email.',
    'need_domain_first' => 'Bạn cần thêm và xác minh tên miền trước.',

    // ─── User Templates ───────────────────────────────
    'email_templates'   => 'Mẫu Email',
    'add_template'      => 'Thêm mẫu',
    'edit_template'     => 'Sửa mẫu',
    'template_name'     => 'Tên mẫu',
    'template_name_placeholder' => 'VD: Email chào mừng',
    'subject_placeholder_tpl' => 'Tiêu đề email',
    'body_html'         => 'Nội dung (HTML)',
    'save_template'     => 'Lưu mẫu',
    'delete_template'   => 'Xóa mẫu này?',
    'delete_template_desc' => 'Thao tác này không thể hoàn tác.',
    'template_saved'    => 'Đã lưu mẫu!',
    'template_save_fail' => 'Lưu mẫu thất bại.',
    'template_deleted'  => 'Đã xóa mẫu.',
    'template_delete_fail' => 'Xóa mẫu thất bại.',
    'no_templates'      => 'Chưa có mẫu nào',
    'no_templates_hint' => 'Tạo mẫu email để tiết kiệm thời gian soạn thư.',
    'last_updated'      => 'Cập nhật lần cuối',

    // ─── User Filters ─────────────────────────────────
    'email_filters'     => 'Bộ lọc Email',
    'add_filter'        => 'Thêm bộ lọc',
    'edit_filter'       => 'Sửa bộ lọc',
    'filter_name'       => 'Tên bộ lọc',
    'filter_name_placeholder' => 'VD: Di chuyển bản tin',
    'condition'         => 'Điều kiện',
    'when'              => 'Khi',
    'then'              => 'Thì',
    'from_contains'     => 'Người gửi chứa',
    'from_equals'       => 'Người gửi bằng',
    'to_contains'       => 'Người nhận chứa',
    'to_equals'         => 'Người nhận bằng',
    'subject_contains'  => 'Tiêu đề chứa',
    'subject_equals'    => 'Tiêu đề bằng',
    'body_contains'     => 'Nội dung chứa',
    'has_attachment'     => 'Có đính kèm',
    'move_to_folder_action' => 'Di chuyển đến thư mục',
    'add_label'         => 'Thêm nhãn',
    'mark_as_read'      => 'Đánh dấu đã đọc',
    'mark_as_starred'   => 'Đánh dấu sao',
    'forward_to'        => 'Chuyển tiếp đến',
    'folder'            => 'Thư mục',
    'label'             => 'Nhãn',
    'priority_order'    => 'Thứ tự ưu tiên (số nhỏ = chạy trước)',
    'save_filter'       => 'Lưu bộ lọc',
    'delete_filter'     => 'Xóa bộ lọc này?',
    'delete_filter_desc' => 'Thao tác này không thể hoàn tác.',
    'filter_saved'      => 'Đã lưu bộ lọc!',
    'filter_save_fail'  => 'Lưu bộ lọc thất bại.',
    'filter_deleted'    => 'Đã xóa bộ lọc.',
    'filter_delete_fail' => 'Xóa bộ lọc thất bại.',
    'no_filters'        => 'Chưa có bộ lọc nào',
    'no_filters_hint'   => 'Tạo bộ lọc để tự động sắp xếp email đến.',

    // ─── User Labels ──────────────────────────────────
    'manage_labels'     => 'Quản lý nhãn email',
    'add_label_btn'     => 'Thêm nhãn',
    'edit_label'        => 'Sửa nhãn',
    'label_name'        => 'Tên nhãn',
    'label_name_placeholder' => 'VD: Quan trọng',
    'color'             => 'Màu sắc',
    'save_label'        => 'Lưu nhãn',
    'delete_label'      => 'Xóa nhãn?',
    'delete_label_desc' => 'Nhãn sẽ bị xóa khỏi tất cả email.',
    'label_saved'       => 'Đã lưu nhãn!',
    'label_save_fail'   => 'Lưu nhãn thất bại.',
    'label_deleted'     => 'Đã xóa nhãn.',
    'label_delete_fail' => 'Xóa nhãn thất bại.',
    'emails_count'      => 'email',

    // ─── Additional Keys ─────────────────────────────
    'select_emails_warning' => 'Vui lòng chọn ít nhất một email.',
    'delete_emails_confirm' => 'Xóa email?',
    'delete_emails_desc'    => 'Các email được chọn sẽ được chuyển vào thùng rác.',
    'email_sent'            => 'Đã gửi email!',
    'draft_saved'           => 'Đã lưu nháp!',
    'enter_domain_warning'  => 'Vui lòng nhập tên miền.',
    'adding'                => 'Đang thêm...',
    'no_labels_yet'         => 'Chưa có nhãn nào',
    'no_labels_hint'        => 'Tạo nhãn để sắp xếp email theo danh mục.',
    'message'               => 'Tin nhắn',

    // ─── Auth messages ────────────────────────────────
    'login_success'     => 'Đăng nhập thành công! Đang chuyển hướng...',
    'register_success'  => 'Đăng ký thành công! Đang chuyển đến trang đăng nhập...',

    // ─── Footer ───────────────────────────────────────
    'footer_system'     => 'Hệ thống quản lý Email',
];
